#pragma once

#include "Cubit/Events/Event.h"
#include "Cubit/KeyCodes.h"

class CB_API KeyEvent : public Event
{
public:
    //Returns the engine-owned physical key code.
    KeyCode GetKeyCode() const { return m_KeyCode; }

    //Returns the input and keyboard categories for key events.
    EventCategory GetCategoryFlags() const override
    {
        return EventCategory::Input | EventCategory::Keyboard;
    }

protected:
    //Stores the physical key associated with a key event.
    explicit KeyEvent(KeyCode keyCode)
        : m_KeyCode(keyCode)
    {
    }

private:
    KeyCode m_KeyCode;
};

class CB_API KeyPressedEvent final : public KeyEvent
{
public:
    //Stores a physical key press and whether GLFW marked it as repeated.
    KeyPressedEvent(KeyCode keyCode, bool repeated)
        : KeyEvent(keyCode), m_Repeated(repeated)
    {
    }

    //Reports whether this press was generated by key repeat.
    bool IsRepeat() const { return m_Repeated; }

    //Returns the static runtime type for key-pressed events.
    static constexpr EventType GetStaticType() { return EventType::KeyPressed; }

    //Returns the runtime type for this key-pressed event.
    EventType GetEventType() const override { return GetStaticType(); }

    //Returns the diagnostic name for this key-pressed event.
    std::string_view GetName() const override { return "KeyPressedEvent"; }

private:
    bool m_Repeated;
};

class CB_API KeyReleasedEvent final : public KeyEvent
{
public:
    //Stores the physical key that was released.
    explicit KeyReleasedEvent(KeyCode keyCode)
        : KeyEvent(keyCode)
    {
    }

    //Returns the static runtime type for key-released events.
    static constexpr EventType GetStaticType() { return EventType::KeyReleased; }

    //Returns the runtime type for this key-released event.
    EventType GetEventType() const override { return GetStaticType(); }

    //Returns the diagnostic name for this key-released event.
    std::string_view GetName() const override { return "KeyReleasedEvent"; }
};

class CB_API KeyTypedEvent final : public Event
{
public:
    //Stores a Unicode code point produced by text input.
    explicit KeyTypedEvent(char32_t codePoint)
        : m_CodePoint(codePoint)
    {
    }

    //Returns the Unicode code point entered by the user.
    char32_t GetCodePoint() const { return m_CodePoint; }

    //Returns the static runtime type for typed-character events.
    static constexpr EventType GetStaticType() { return EventType::KeyTyped; }

    //Returns the runtime type for this typed-character event.
    EventType GetEventType() const override { return GetStaticType(); }

    //Returns the diagnostic name for this typed-character event.
    std::string_view GetName() const override { return "KeyTypedEvent"; }

    //Returns the input and keyboard categories for this event.
    EventCategory GetCategoryFlags() const override
    {
        return EventCategory::Input | EventCategory::Keyboard;
    }

private:
    char32_t m_CodePoint;
};
